name: Run Tests

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - .github/workflows/tests.yml
  pull_request:
    branches:
      - master
    paths:
      - src/**
      - .github/workflows/tests.yml

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: "3.10"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk
          sudo apt-get install -y python3-pil python3-pil.imagetk

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install package
        shell: bash -l {0}
        run: pip install .

      - name: Run Tests
        shell: bash -l {0}
        run: |
          python -m unittest -v
