name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/tests.yml
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/tests.yml
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk
          sudo apt-get install -y python3-pil python3-pil.imagetk

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install package
        shell: bash -l {0}
        run: pip install .

      - name: Run Tests with coverage report
        shell: bash -l {0}
        run: |
          python -m unittest -v --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
