name: Run Tests

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - .github/workflows/tests.yml
  pull_request:
    branches:
      - master
    paths:
      - src/**
      - .github/workflows/tests.yml

jobs:
  test:
    runs-on: ubuntu-latest  # Latest version of Ubuntu

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]  # Python versions to test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |  # Install Tkinter and Pillow dependencies for ClassiPyGRB
          sudo apt-get update
          sudo apt-get install -y python3-tk
          sudo apt-get install -y python3-pil python3-pil.imagetk

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |  # Upgrade pip
          python -m pip install --upgrade pip

      - name: Install package  # Install ClassiPyGRB and dependencies
        shell: bash -l {0}
        run: pip install .

      - name: Run Tests  # Run tests
        shell: bash -l {0}
        run: |
          python -m unittest -v
